title: A-NZ Industry Practice Statements
description: >
  
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme
sass:
  style: expanded
# Point to the custom CSS
just_the_docs:
  css:
    - assets/css/custom.css

# Navigation (will show in sidebar/top depending on theme)
nav:
  - title: Home
    url: /
  - title: Guidance and Recommendations for Consistent Data Mapping
    url: /A-NZ ASWG_Consistent Data Mapping
  - title: Guidance And Recommendations For Access Point Migration And Exit
    url: /A-NZ Industry Practice Statement_AP Migration and Exit
    
